info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: ERROR
    org.springframework: ERROR
  profile: CLOUD

security:
  basic:
    enabled: true
    realm: sdc
  user:
    name: admin
    password: secret

management:
  security:
    roles: SUPERUSER
    enabled: true
  health:
    rabbit:
      enabled: false

server:
  port: 8171
  servlet-path: /

spring:
  application:
    name: ONS SDC Int Mock Service

redelivery-policy:
  maxRedeliveries: 10
  initialRedeliveryDelay: 1000
  redeliveryDelay: 1000

report-settings:
  cron-expression: "0 * * * * *"

swagger-settings:
  swagger-ui-active: false
  group-name: sdc-int-mock-service-api
  title: SDC INT Mock Service API
  description: API for ${project.artifactId}
  version: ${project.version}

retries:
  maxAttempts: 3
  backoff: 5000
